# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Dynamics
author: SpaceHQ
logo: logo.png
# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
